### PR TITLE
Enhanced  navbar

### LINKED ISSUE #185: [UI] Navbar
**Description**
The whole navbar is degrading the website

**Current Behavior**
It sis very basic and has 0 to no styling

**Proposed Behavior**
It should attract users and improve user experience.

**Screenshots**
image

**Additional Context**
**Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.**

**Impact**
Imporve visual appeal

### PR DESCRIPTION
**Pull request by Bhum-ika**
## 📋 Description

I have edited the Navbar to make it look more appealing, fixed the responsiveness issue

## 🔨 Changes Made

1. Added Padding to navbar
2. Edited hover effects and added transition
3. Redesigned Login and Register buttons
4. Made the navbar fixed to whole width on mobile screens

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

- Fixes #185 

## 📸 Screenshots (if applicable)
After
image

Before
image

https://github.com/user-attachments/assets/08779fa1-f485-4dac-a362-8ce42c8dd22d

If you liked my work, I'd really appreciate if you add level3, I spent half of my day on it
Kindly add all tags while merging PR.

### CODE REVIEW

**Comment by Sowmiyajayakumar** [comment]
Hey @Bhum-ika, between 768px to 990px the navbar is looking quite odd. 
image

**Comment by Sowmiyajayakumar** [comment]
For the desktop view, keep the bg color of register button as white and the font color of active tab as white itself.

**Comment by Bhum-ika** [comment]
Okay, let me fix it

**Comment by Bhum-ika** [comment]
Please check 
Also, i can't check the changes between 768px to 990px , navbar not working

**Comment by Sowmiyajayakumar** [comment]
Hey @Bhum-ika, looks good! can you make the font color of register button as white ON HOVER

**Comment by Bhum-ika** [comment]
Done, please have a look

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Comment by Bhum-ika** [comment]
Hey @Vignesh025 could you please add level 3 here

**Comment by Vignesh025** [comment]
Hey @Bhum-ika , as per the instructions, I can only assign level 2 for this PR.

**Pull request merged**
