### PR TITLE
Add [feature/fix]: [Fixed the Login UI by redesigning it]

### PR DESCRIPTION
**Pull request by itsadi-24**
## 📋 Description

I redesigned the Login UI and add placeholders for the input fields.

## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [✅] My changes generate no new warnings.
- [✅] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [✅] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

Screenshot 2024-10-13 162133

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by itsadi-24** [comment]
@Vignesh025 merge this

**Comment by itsadi-24** [comment]
also include the labels hacktoberfest-accepted gssoc-ext

**Comment by Vignesh025** [comment]
I'm happy with the UI. Can you do the same for the register page in the same PR or as a separate PR?

**Comment by itsadi-24** [comment]
> I'm happy with the UI. Can you do the same for the register page in the same PR or as a separate PR?
Sure i will do it as a separate PR.I guess you already have another issue regarding the Resgister Page i will do that.

**Comment by itsadi-24** [comment]
@Vignesh025  Sure i will do it as a separate PR.I guess you already have another issue regarding the Resgister Page i will do that.

**Comment by Vignesh025** [comment]
@itsadi-24 , you can proceed. Once you create a PR for register, I'll merge your both PRs to ensure uniformity in the UI.

**Comment by itsadi-24** [comment]
@Vignesh025 Sure I will do it

**Comment by itsadi-24** [comment]
@Vignesh025 can you check and tell

**Comment by Vignesh025** [comment]
@itsadi-24 Still the login.ejs is conflicting

**Comment by itsadi-24** [comment]
Ok i'm looking onto it

**Comment by itsadi-24** [comment]
@Vignesh025 done pls check

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
