### PR TITLE
added scroll to top feature

### LINKED ISSUE #103: [FEATURE] Adding scroll to top button
**Is your feature request related to a problem? Please describe.**
When navigating downward in campgrounds page, it becomes cumbersome to scroll back to the top manually, especially on mobile devices. This impacts user experience, making it harder to navigate.

**Describe the solution you'd like**
I would like to add a "Scroll to Top" button that appears after the user has scrolled down a certain amount. Clicking this button will smoothly scroll the page back to the top.

**Describe alternatives you've considered**
An alternative could be adding a fixed "Back to Top" link in the footer, though a floating button provides a better user experience across devices.

### PR DESCRIPTION
**Pull request by Durga-prasad-1**
## 📋 Description
I have added scroll to top feature.
"Scroll to top" is a user interface feature found on websites or applications that allows users to quickly return to the top of a page with a single click or action. It is typically represented by an arrow or button that appears once the user scrolls down a certain distance.

## 🔨 Changes Made

this pr made a change that is added a new feature ,
[FEATURE] Adding scroll to top button #103

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] New feature (non-breaking change which adds functionality) ✨

## 🤝 Related Issues

the related issue of this PR is #103 

- Fixes #103 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/5d837995-ea90-4fb1-afe3-e5de0eb9fbfa

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hey @Durga-prasad-1, could you please update the style of the icon? That would be nice.

**Comment by Durga-prasad-1** [comment]
@Vignesh025 Sure,  Could you please let me know what kind of styling you prefer for the icon?

**Comment by Vignesh025** [comment]
image

something like this and small

**Comment by Vignesh025** [comment]
Could you please change the color to match the navbar? Thank you!

**Comment by Durga-prasad-1** [comment]
please check it

**Comment by Vignesh025** [comment]
I'm happy with the design of the button. Please sync your fork, and I'll merge it.

**Comment by Durga-prasad-1** [comment]
@Vignesh025 The fork has been synced. You can go ahead with the merge .

**Comment by Vignesh025** [comment]
Your fork is still many commits behind. Please sync again.

**Comment by Durga-prasad-1** [comment]
@Vignesh025 i have made the sync now please check it again

**Comment by Vignesh025** [comment]
*Thank you for Contributing!*

**Pull request merged**
