### PR TITLE
Changes for Prevent spam review ISSUE #169

### LINKED ISSUE #169: [BUG] Spamming in review
**Describe the bug**
In view campground page where login user should allowed to leave a review. Here for now one user can leave more than one means unlimited review, for this cause a spamming chance. Which might be vulnerable issue for database.
 
**To Reproduce**
1. Go to 'Campgrounds'
2. Click on 'View Campground'
3. Here you can see one user free to add more than one review.
4. See error in the attached video

**Expected behavior**
It need to prevented form this. The expected behaviour is One logged in user should allowed to leave only one review only for one campground display. If they delete the review only then allowed to leave new reeview again.
**Screenshots**

https://github.com/user-attachments/assets/67160067-73a1-43b4-915c-c86aff4e5ce9

*Please assign me this ISSUE, It's an serious issue. Need to fix this.*

**Don't forget to add necessary labels. including hacktoberfest-accepted.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
## 📋 Description

Changes done for preventing Review Spamming. Add both backend and frontend logic

## 🔨 Changes Made

- Fixes #169 
- Changes made in show.ejs, campground.js & review.js controller
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #169 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/f15bd4c0-cc30-4a0c-9b08-c3193288f4ff

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

@Vignesh025   Please have a look and marge this ASAP. And don't forget to add all the labels that are in #169 issue, That is `label-2`, `gssoc-extd`, `hacktoberfest-accepted`

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@Vignesh025 
Please marge it and also add all the labels.

**Comment by Sowmiyajayakumar** [comment]
Hey @Suvadip-sana , code is breaking. please check if you've pushed all your changes.
image

**Comment by Suvadip-sana** [comment]
@Sowmiyajayakumar 
I don't work on navbar. This is not my fault.

**Comment by Suvadip-sana** [comment]
@Vignesh025  Please check and marge it. Please.

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , I'm unable to submit any reviews. When I try to submit, I'm getting an error. please check and resolve it.

image

**Comment by Suvadip-sana** [comment]
@Vignesh025 
After check this I inform you.

**Comment by Suvadip-sana** [comment]
@Vignesh025 
Now check. I think It's resolved now.
If solved then add all the tags that are in ISSUE #169  and marge it.

**Comment by Suvadip-sana** [comment]
@Vignesh025  Check it please.

**Comment by Suvadip-sana** [comment]
@Vignesh025  Any update?

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , your code works fine! Just resolve the conflicts, and I'll go ahead with the merge.

**Comment by Suvadip-sana** [comment]
@Vignesh025  
Solved. Please marge it. And don't forget to add all the labels as per the ISSUE #169

**Comment by Vignesh025** [comment]
@Suvadip-sana, application is not running after you resolved the conflicts. please check

**Comment by Suvadip-sana** [comment]
@Vignesh025 
Is your test branch and main branch completely synced? 
At first you tell me one thing. 
When I try to solve the conflict. There is not only my code. There is exist other stuff. So except my code I comment out rest of other. 
Though it's not your main branch. It's test branch. So should I directly make changes on test branch in my local machine? Then it's more clear to me! Tell me what to do fast?

**Comment by Suvadip-sana** [comment]
@Vignesh025 
Sorry for the misunderstanding. I will fix it. And inform You.

**Pull request closed without merging**
