### PR TITLE
Feature/register UI enhancement

### PR DESCRIPTION
**Pull request by itsadi-24**
## 📋 Description

I have improved the register page ui and added placeholders

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [✅] My changes generate no new warnings.
- [✅] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [✅] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 📸 Screenshots (if applicable)

Screenshot 2024-10-14 120634

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by itsadi-24** [comment]
@Vignesh025 You can merge this and also add the labels hactober-accepted and gssoc-ext.Thanks!

**Comment by itsadi-24** [comment]
Hi @Vignesh025 i have also fixed the merge conflict in this,you can accept and merge this

**Comment by Vignesh025** [comment]
Hey, when the validation message is displayed, the eye icon shifts its position. Please make sure the icon stays stable.
image

Also resolve the conflicts.

**Comment by itsadi-24** [comment]
Ok i'm working on it

**Comment by itsadi-24** [comment]
Screenshot 2024-10-16 152313
Hi @Vignesh025  i have fixed it,you can merge it and add the labels.Thanks!

**Comment by Vignesh025** [comment]
can you fix the same bug in the login page? That would be great.

**Comment by itsadi-24** [comment]
Sure working on it

**Comment by itsadi-24** [comment]
Screenshot 2024-10-16 230051
you can check it @Vignesh025

**Pull request merged**
