### PR TITLE
Enhancing the contributor Section and Structuring

### LINKED ISSUE #294: Enhancing the contributor Section and Structuring
## Description

The goal is to enhance the Contributor section of the README and improve its structure for better clarity and presentation. This may involve updating contributor information, adding images or badges, and reformatting the layout for better readability.

**Affected Pages**:
- [x] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

The current Contributor section may lack visual appeal or sufficient organization. A more structured and visually engaging layout can highlight the contributions of individuals more effectively. Possible suggestions could include adding badges, aligning contributor details, or grouping by contribution types. If applicable, screenshots can be shared to show the before and after state of the Contributor section for reference.

## Suggested Improvements

- **Reformat Contributor Section**: Use a grid layout to make the section visually appealing and organized.
- **Add Images**: Display contributor GitHub avatars with a consistent size.
- **Include Links**: Add links to each contributor's GitHub profile directly.
- **Use Badges**: Include badges that showcase contributions such as "Maintainer," "Top Contributor," or specific GitHub activity (stars, forks).
- **Group Contributors**: Categorize contributors based on the type of contribution (e.g., code, documentation, design).
- **Include Automation**: Consider using GitHub tools like `all-contributors` to automate the addition and maintenance of contributors.

---

Feel free to tweak any part based on your specific requirements!

### PR DESCRIPTION
**Pull request by alo7lika**
## 📋 Description

Enhancing the Contributor Section and improving the structure for better readability and engagement.

## 🔨 Changes Made

- Updated contributor graph to use the Vaunt API for dynamic contributor visuals.
- Structured the contributor section for better presentation.
- Added responsive alignment for the contributor images.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #294 

## 📸 Screenshots (if applicable)
Screenshot 2024-10-26 221619

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by alo7lika** [comment]
@Vignesh025 The task has been completed.

**Comment by Vignesh025** [comment]
Hey @alo7lika , Please solve the conflicts.

**Comment by alo7lika** [comment]
> Hey @alo7lika , Please solve the conflicts.

Solved, also the level was assigned 2 in #294 and here you have assigned level 1

**Comment by Vignesh025** [comment]
I changed the level to 1 since the changes were small.

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
