### PR TITLE
Logo added

### PR DESCRIPTION
**Pull request by shreyad2806**
## 📋 Description

Added logo in the home page and navbar

## 🔨 Changes Made

#80 
- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

Screenshot 2024-10-06 231437

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Vignesh025** [comment]
@shreyad2806  please add the logo image in the PR body.

**Review by Sowmiyajayakumar — COMMENTED** [review]
In the logo, remove "Go Explore" and make CampX text larger because it will not be visible clearly.

**Comment by Sowmiyajayakumar** [comment]
Can you remove the dotted underline also in the logo?

**Comment by shreyad2806** [comment]
Added the new logo!

**Comment by Vignesh025** [comment]
Please move the ``logo.png`` file to the ``icons`` folder in the ``public`` directory. Make sure there’s only one instance of ``logo.png``. Also, set the logo as the web icon (favicon) only, and remove it from the navbars.

**Pull request closed without merging**
