### PR TITLE
[FEATURE] Provide an option to sort campgrounds based on current location of the user #18

### LINKED ISSUE #18: [FEATURE] Provide an option to sort campgrounds based on current location of the user
**Issue**
When the user registers and views all the campgrounds he will have a button in the /campgrounds route which has all the campgrounds to sort all them from his current location. This will be handy as he/she won't have to look through the map to find the closest campgrounds. 

**Solution**
A button to show the nearest campgrounds based on users location

### PR DESCRIPTION
**Pull request by memyselfandglitch**
## 📋 Description

When the user logs in and views all the campgrounds he will have a button in the /campgrounds route (which has all the campgrounds) to sort all of them from his current location. This will be handy as he/she won't have to look through the map to find the closest campgrounds.

## 🔨 Changes Made

Fixes #18 

Created a route called /nearest that will be called along with query params of latitude and longitude on clicking the button using the geolocation API. Subsequent function called showNearestCampgrounds is in the controller directory of campgrounds that sorts the campgrounds based on latitudes and longitudes using turf package.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [✅] I have commented my code, particularly in hard-to-understand areas.
- [✅] I have made corresponding changes to the documentation (if applicable).
- [✅] My changes generate no new warnings.
- [✅] I have tested it locally and it works fine.
- [✅] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [✅] New feature (non-breaking change which adds functionality) ✨
- [✅] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #18 

## 📸 Screenshots (if applicable)
Screenshot 2024-10-01 at 00 39 59
Screenshot 2024-10-01 at 00 40 29
Screenshot 2024-10-01 at 00 40 40

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hi @memyselfandglitch ,

Thank you for your pull request! I tried running it locally, but it seems the sorting by user location isn't working as expected. Could you please take a look at it, investigate the issue, and make any necessary adjustments?

Let me know if you need any assistance. Looking forward to the updated version!

Thank you!

**Comment by memyselfandglitch** [comment]
I think it could be because I didn't add my cloudinary link where the pictures are uploaded. I will try again. While syncing I ran into some merge conflicts and I am not sure how to fix that is it fine if I create a new PR?

**Comment by Vignesh025** [comment]
@memyselfandglitch ,I’m not sure where the error lies, but your code works mostly as intended.But the places in Karnataka are closer to me, while the places in Kerala appear farther away. However, in the screenshots, it seems to be the opposite.

image
Other places seem to be accurate, though. Do you think you can improve this, or is this the most accurate the code can achieve?

**Comment by memyselfandglitch** [comment]
I just reviewed the logic and I made a mistake. While calculating the distance I used the user's longitude,latitude and the camground's latitude,longitude so there was an error. Fixed it. Let me know if it helps it. Sorry about the inconvenience.

**Comment by Vignesh025** [comment]
*Thank you for Contributing!*

**Pull request merged**
