### PR TITLE
Implemented forgot password functionality

### LINKED ISSUE #351: [FEATURE] : Implementing OTP based forgot password route (Backend + frontend)
**Is your feature request related to a problem? Please describe.**
it allows users to reset their password if they forgot it, enabling them to login to their account

**Describe the solution you'd like**
I wanted to add backend and frontend of the functionality so that users can reclaim their account even if they forgot their password

Workflow: 
1. user enters their registered email
2. and otp is sent to their email
3. user verifies that otp
4. user reset Their password

image

### PR DESCRIPTION
**Pull request by Sourabh782**
## 📋 Description
Closes #351 

## 🔨 Changes Made

- Implemented otp based forgot password functionality
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] My changes generate no new warnings.
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #351 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/4ed94e51-7303-4a51-b1d8-1c05631825d7

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Vignesh025** [comment]
@Sourabh782 , Could you please specify all the items that need to be included in the .env file?

**Comment by Sourabh782** [comment]
> @Sourabh782 , Could you please specify all the items that need to be included in the .env file?

really sorry ill add them on sample.env just a min

**Comment by Sourabh782** [comment]
@Vignesh025 added sample env file

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
