### PR TITLE
Added the auto search on entering by user

### LINKED ISSUE #159: [FEATURE] Improving the search functionality continous searching as the user enters the text in search box.
Improving the search functionality continous searching as the user enters the text in search box.

@Vignesh025 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
## 📋 Description

Added the auto search on entering by user. It will now search automatically search with a debounce you don't need to again and again click on the search button.

## 🔨 Changes Made

Fixes #159 

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] My changes generate no new warnings.
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [X] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

@Vignesh025 Please check this PR and merge it and assign this to me and put relevant labels such as gssoc 2024 ext, hacktoberfest and level.

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005 , While typing each letter, the whole page reloads, and dynamic search is not working as expected. Please look into this.

**Comment by tarunkumar2005** [comment]
@Vignesh025 It is reloaded because the function you are triggering on form submit reloads the page. That's why it is happening. We need to define a proper custom function with js for the handling, then it can be fixed.

**Comment by tarunkumar2005** [comment]
you have directly used action="/route" like that in form tag only thats the reason it is reloading with every search if you click on search it will reload then also.

**Comment by tarunkumar2005** [comment]
@Vignesh025     <form action="/campgrounds/search" method="GET" class="form-inline my-2 my-lg-0" id="search-form">

this one so what you wants me to do ??

**Comment by tarunkumar2005** [comment]
You can either merge this or increase the level of the PR i will update this and try to avoid this reload over and over and dynamically submit the form without reloads.

**Comment by Vignesh025** [comment]
@tarunkumar2005 , you can proceed!

**Comment by tarunkumar2005** [comment]
@Vignesh025 Will do that and update the PR soon

**Comment by tarunkumar2005** [comment]
@Vignesh025 Bro done the change please make it level 3 now took so much time to do this and for the testing i have used demo data i have removed that also while pushing the code as i don't have database you can test it with the database data of the campsites okay and here is video demo page is not reloading now :- 

https://drive.google.com/file/d/1kYrbzww78bnPtRr1ZNmBhUSO7w8EARym/view?usp=sharing

I have tried to use best practices and improved the code also.

**Comment by Vignesh025** [comment]
Hey, your code is breaking the campground page. The campgrounds are not visible anymore. Please look into it and make the necessary corrections.

**Comment by tarunkumar2005** [comment]
@Vignesh025 I don't have your real data can you share the database data or connection link then i will be able to properly test it what is the issue just breaking can't elobrate what is the issue also can you share screenshots where you are finding issue.

**Comment by Vignesh025** [comment]
Hey, database links aren't meant to be shared. Please create your own MongoDB account and use it for development. Just check with 5 campgrounds—that's more than enough for testing. I'm attaching screenshots of the errors below.

image

image

**Comment by Vignesh025** [comment]
Do you have discord?

**Comment by tarunkumar2005** [comment]
@Vignesh025 Dm me on linkedin on my profile there is link otherwise on discord this is my username :- tarunkumar8278

**Comment by tarunkumar2005** [comment]
@Vignesh025 I have done the changes if you could have provided the database it will have a better testing, i tried to do it properly i think there will be no issue now if you find any please mention me i will try to fix that but it is problemetic without the db, like if you could provide a copy of database just that collection in which the api data is there then it would have been easy but no worries i have tried to do it with the sample data you gave please check it now.

**Comment by tarunkumar2005** [comment]
@Vignesh025 I know how to connect mongodb that is not the problem i wanted your database as your application is running on that and why it is showing error in your case in my case it was running fine ??

**Comment by tarunkumar2005** [comment]
@Vignesh025 Sorry can you check again my mistake just a word i missed in the syntax i will update sorry then you can again check and tell me if it is okay or not.

**Comment by tarunkumar2005** [comment]
now check once... if it is working or not.

**Comment by Sowmiyajayakumar** [comment]
Hey @tarunkumar2005, still facing the same issue...campgrounds are not visible in campgrounds page.
image
image

**Comment by tarunkumar2005** [comment]
@Sowmiyajayakumar @Vignesh025 I have done all the things if you can just put up little efforts to properly integrate it with the backend data you are getting of the campgrounds then it will be working as you are not ready to give the database and i completly agree that you might have security conserns for this but i can't do much in this without database as i have done the frontend but i don't know how the data is coming from the backend oor how i should hanlde it then i can't do much in it so if you can merge it in a test branch or something like that and put a level 2 insted of level 3 then it is fine by me or else you can provide me database then i can integrate it or you can try to integrate this small thing by yourself so that you don't have to share the database.

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005 , We already provided you with enough data. You asked for the JSON, and I sent it to you. I even shared the seeds file, which, if run with your user ID, will create your own database. Also, it's important to note that you should not refer to this as a 'small thing' and then ask us to handle it. We are managing the whole project, and nobody else has raised concerns about the database, so please don't shift the blame.

**Comment by tarunkumar2005** [comment]
@Vignesh025 Okay i am not blaming i was just saying i don't know how the data if formatted in the database just that. i will try a little bit more on this, if i can fix this okay i will try my best with the limited data i have okay so wait until tomorrow i will update you on this. sorry if you felt bad from my statement.

**Comment by Vignesh025** [comment]
Hey @tarunkumar2005, It's not limited data—it's the actual data that the project runs on. I uploaded the data to the database in the same way that I'm asking you to do. Just follow the same process, and it will work as expected. Also no need to apologize.

**Comment by tarunkumar2005** [comment]
@Vignesh025 Check now i have updated and now it is perfectly fine please check now if it is working for you also.

**Comment by Sowmiyajayakumar** [comment]
Hey @tarunkumar2005 , search functionality is working perfectly now. But please remove the below highlighted buttons 
image

**Comment by Sowmiyajayakumar** [comment]
Also please make the PR to test branch.

**Comment by tarunkumar2005** [comment]
@Vignesh025 @Sowmiyajayakumar Done the changes check now.

**Comment by Sowmiyajayakumar** [comment]
Hey @tarunkumar2005, dynamic search is not working now...please check if all your dynamic search changes are there

**Comment by tarunkumar2005** [comment]
@Vignesh025 @Sowmiyajayakumar Done wiht the changes the issue was in backend it was rendering instead of returning so i have fixed that now check it is working completly fine.

**Comment by Vignesh025** [comment]
Congratulations on completing the PR! I know it took quite a few days, so great job seeing it through to the end!

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
