### PR TITLE
Review section improvement

### LINKED ISSUE #248: [FEATURE] Feature improvement in 'Reviews' section
**Is your feature request related to a problem? Please describe.**
In review section where the reviews are displayed. If one place does not have any review then simply it's display nothing. As a user they missed out this important review section for missing this gesture. So it's need to display something like this "No review posted yet" If the camping site doesn't have any review.

**Describe the solution you'd like**
If the reviews are there then it should be displayed like this:
image

And if there is no review posted yet for a property then this section looks like this:
image

**Additional context**
For now your website looks like this. Which is not understandable for displaying reviews.
image

@Vignesh025  Please assign me this ISSUE. It's need some backend logic to implement this gestures.  And I want to implement this logis.

### PR DESCRIPTION
**Pull request by Suvadip-sana**
## 📋 Description

i modify in`show.ejs` file.
Where it display a msg if no review is posted yet for a campground

## 🔨 Changes Made

-  In `show.ejs` file

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #248 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/795dcc41-dc17-4c9f-b08c-995ddd7a53a6

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### @Vignesh025   Please marge it. And don't forget to add all the labels same as the ISSUE #248

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hey @Suvadip-sana , Have this sentence
"No review(s) yet"

**Comment by Suvadip-sana** [comment]
@Vignesh025 
I didn't understand

**Comment by Vignesh025** [comment]
change the sentence from "No review posted yet." to "No review(s) yet"

**Comment by Suvadip-sana** [comment]
image
@Vignesh025 
Done. Marge it

**Comment by Suvadip-sana** [comment]
@Vignesh025 ?

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
