### PR TITLE
Enhances the structure and also added some new sections

### LINKED ISSUE #215: [DOC]: Enhancement Of Contributing.md
## Description

The contributing.md looks is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

**Affected Pages**:
- [ ] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [x] CONTRIBUTING.md
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

-----------------------

## Suggested Improvements

Wanted to do the following changes :-

1) Enhance the project structure
2) Add project structure section
3) Add additional method of contributing through GitHub desktop section
4) Add good coding practices section
5) Add the help and support section
6) Add the pull request section
7) Add issue report process section

---

### PR DESCRIPTION
**Pull request by milansamuel609**
## 📋 Description

I have done some enhancements in the structure of the file and also added some new sections.

## 🔨 Changes Made

Fixes:[#215 ]

I have done these changes :-

1) Enhanced the project structure
2) Added need help with the basics section
3) Added project structure section
4) Added additional method of contributing through GitHub desktop section
5) Added good coding practices section
6) Added the help and support section
7) Added the pull request section
8) Added issue report process section

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues

- Fixes #215 

## 📸 Screenshots (if applicable)

Screenshot 2024-10-18 221919

Screenshot 2024-10-18 221930

Screenshot 2024-10-18 221939

Screenshot 2024-10-18 222006

Screenshot 2024-10-18 222017

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have done all the enhancements. Please kindly check it once.

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , under the 'Help and Support' section, please add my profile link for the admin—right now it's just the name. Also, for the contact email, start the link with 'mailto:' so it works correctly. Lastly, in the issue report process, ask contributors to use the template when submitting issues. Thanks!

**Comment by milansamuel609** [comment]
@Vignesh025  I have updated the changes that you have asked for. Please kindly check once.

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , My profile link is https://github.com/Vignesh025
you've added the organization link. 
kindly replace this.

**Comment by milansamuel609** [comment]
I have updated the changes. Instead of admin I wrote admin github profile and also added your mail id and github profile. Please kindly check it once.

**Comment by Vignesh025** [comment]
Please have vigneshdevhub@gmail.com as the mail.

**Comment by milansamuel609** [comment]
> Please have [vigneshdevhub@gmail.com](mailto:vigneshdevhub@gmail.com) as the mail.

Sure I will do it right now.

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Comment by milansamuel609** [comment]
Actually this PR is not counted as contribution in gssoc extended. Please kindly assign this PR to me and please label it as gssoc ext and also add the level.

**Comment by milansamuel609** [comment]
Please select the assigned member as me also. Otherwise they will not able to verify the assigne.

**Comment by Vignesh025** [comment]
Assignee does not matter. The assignee is the reviewer.

**Comment by milansamuel609** [comment]
> Assignee does not matter. The assignee is the reviewer.

No actually the gssoc community told me like this because my points we not update thats why. They told me these points :(

These are the important things :-

PR should be merged.
It should be assigned.
It should be labeled gssoc, and respective level such as level1, level2, level3.

**Pull request merged**
