### PR TITLE
[UI] Enhance navbar

### PR DESCRIPTION
**Pull request by RanitDERIA**
## 📋 Description

This pull request enhances the navbar in the CampX web application to provide a better user experience and improved accessibility.

## 🔨 Changes Made

- Implemented responsive design enhancements to ensure the navbar adapts seamlessly across all screen sizes.
- Added hover effects and improved the link arrangement for better clarity and usability.
- Introduced dropdown menus for better organization of content.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] I have commented my code, particularly in hard-to-understand areas.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] UI enhancement (non-breaking change which enhances UI) 🎨

## 📸 Screenshots
*Large Screen:*
Screenshot (409)

*Medium Screen:*
Screenshot 2024-10-08 002608

*Small Screen:*
Screenshot 2024-10-08 002222

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by RanitDERIA** [comment]
Hey @Vignesh025 , 

I noticed the auto labeler is failing with the error: `HttpError: Resource not accessible by integration`. It seems like a permissions issue with the GitHub Action. Could you check the configuration or token permissions? Thanks!

**Comment by Vignesh025** [comment]
Your code is breaking. Please undo all the deletions made in the ``app.js`` file.

**Comment by Vignesh025** [comment]
The code is still breaking, and it's showing that ``currentpath`` is not defined in ``navbar.ejs``. Please check and resolve this issue.

**Comment by RanitDERIA** [comment]
The issue with `currentPath` not being defined in `navbar.ejs` is resolved. I added a middleware in `app.js` to pass `currentPath` to all views, ensuring it can be properly accessed and used throughout the application.

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
