### PR TITLE
Enhanced the file

### LINKED ISSUE #250: [DOC] : Enhancement Of README.md
## Description

The README.md file is kind of incomplete and more sections can be added in it. 

**Affected Pages**:
- [x] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Please add any other context or screenshots about the documentation issue or suggestion here.

## Suggested Improvements

I can enhance it in a more structured manner and also can add some new sections.

---

### PR DESCRIPTION
**Pull request by milansamuel609**
## 📋 Description

The README.md file was not in a structured manner. Also some sections are missing. I have enhanced it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

## 🔨 Changes Made

I have done only these changes:

1) Enhanced the structure
2) Enhanced the installation guide
3) Added troubleshooting
4) Added help and support
5) Added thank you session

Fixes:[#250 ]
Closes:[#250 ]

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues

- Fixes #250 

## 📸 Screenshots (if applicable)

Screenshot 2024-10-22 120754

Screenshot 2024-10-22 120810

Screenshot 2024-10-22 120820

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by milansamuel609** [comment]
Sorry I was mistakenly connecting to the main branch instead of test branch. Now I have connected to the test branch. Please kindly check the changes and merge the PR if all are fine. Also please attach the gssoc extend and level label

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , make sure you have the forks,stars,issues,PRs badges.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609 , make sure you have the forks,stars,issues,PRs badges.

Yes I have I am forking and starring every single repository that I am contributing to 👍

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , No, you misunderstood. I said I need the below badges, but without the table format.

image

**Comment by milansamuel609** [comment]
Please check the updated file once. The only issue is that I am not able to do is aligning the headings of each item like star and same for other. Leaving that I have fixed other things.

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , I wanted you to add the badges in the Readme.md file but you made the changes to the contributing.md file. Also you've added a image to the project , I can't see it anywhere. so if you're not using it anywhere please remove it.

**Comment by milansamuel609** [comment]
> Hey @milansamuel609 , I wanted you to add the badges in the Readme.md file but you made the changes to the contributing.md file. Also you've added a image to the project , I can't see it anywhere. so if you're not using it anywhere please remove it.

But like you havent mentioned about the readme.md file so I thought I have to add in the contributing.md itself. I am sorry about that and also about that images that you are telling. Let me fix that quickly.

**Comment by milansamuel609** [comment]
I have updated the contributing.md file. Can you please specify like where you have seen that image? Actually I am not able to spot it.

**Comment by Vignesh025** [comment]
> I have updated the contributing.md file. Can you please specify like where you have seen that image? Actually I am not able to spot it.

You just added the image as a file image.png

**Comment by milansamuel609** [comment]
It was my mistake. I mistakenly after updating the readme file I have inserted the star repository instruction in the contributing.md. From next not a single mistake will happen from my side. I apologize but I know there's no meaning in my apologize but still I am sorry. I am really sorry for the inconvenience caused to you. If you want please withdraw this assignment. 😔

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , mistakes happen. Don't worry about it. Its just part of learning.

**Comment by Vignesh025** [comment]
Hey @milansamuel609 , remove the code from line 7 to line 31 in readme.md

**Comment by milansamuel609** [comment]
I have removed it please kindly check once.

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
