### PR TITLE
Fix/alignment of search bar

### LINKED ISSUE #178: [UI] alignment correction
**Description**
Responsive issue 

**Current Behavior**
Search bar is not responsive 

**Proposed Behavior**
I will fix the size and align the search bar portion 

**Screenshots**
Screenshot_2024-10-14-08-53-42-613_com android chrome

**Additional Context**
Add any other context, such as references to design guidelines, user feedback, or examples from other applications.

**Impact**
Explain the potential impact of this change. Will it improve usability, accessibility, performance, or visual appeal?

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

### PR DESCRIPTION
**Pull request by Nbisht1208**
## 📋 Description
issue #178 
Make search section responsive and fix alignment 

## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ✅] Bug fix (non-breaking change which fixes an issue) 🐛

## 🤝 Related Issues

make the search section responsive and fix the alignment 

- Fixes #178

## 📸 Video  of responsive search bar

https://github.com/user-attachments/assets/7d400703-f350-4c0e-b1ee-a51d78166e69

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hey @Nbisht1208 , You've made the PR to the main branch. Please raise the PR to the test branch.

**Comment by Nbisht1208** [comment]
@Vignesh025 done

**Comment by Vignesh025** [comment]
Hey @Nbisht1208 ,Please resolve the conflicts.

**Comment by Nbisht1208** [comment]
@Vignesh025 done ✅

**Comment by Sowmiyajayakumar** [comment]
Hey @Nbisht1208 , Sorry that alignment issue is already fixed.

**Pull request closed without merging**
