### PR TITLE
Add [feature]: Grid Layout of Campgrounds

### LINKED ISSUE #115: [UI] Show All Campground using grid view
**Description**
I will make all campground cards show using grid view in which it will show as 3 cards in one row in desktop view, 2 cards per row in tablet view and 1 card per row in mobile view.

**Current Behavior**
Currently it is showing one long card per row with not having much content. So it is not looking good coz user need to scroll too much to find campground.

**Proposed Behavior**
Making 3 cards per row and also making it responsive for mobile also.

**Screenshots**
If applicable, add screenshots or mockups to help explain the proposed change.

**Additional Context**
Add any other context, such as references to design guidelines, user feedback, or examples from other applications.

**Impact**
Better user experience

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

### PR DESCRIPTION
**Pull request by MitulSonagara**
## 📋 Description

I have fixed the campground layout using grid layout

## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation (if applicable).
- [X] My changes generate no new warnings.
- [X] I have tested it locally and it works fine.
- [X] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [X] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #125 
- Fixes #115 

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@Vignesh025 

Please review this and merge it

**Comment by Vignesh025** [comment]
It's still the same. Everything is breaking.

**Comment by MitulSonagara** [comment]
@Vignesh025 

this is working fine on my local system
image

i didnt uploaded the pics thats why it is looking like this

**Comment by Vignesh025** [comment]
> this is working fine on my local system 
Look at the navbar 
compare it with the deployed website
you can see the difference
also appearance wise we can see some padding changes

**Comment by MitulSonagara** [comment]
@Vignesh025 

only navbar issue is there?

**Comment by Vignesh025** [comment]
> only navbar issue is there?

There are few padding issues as well. If you check it with the deployed website, you'll notice.

**Comment by MitulSonagara** [comment]
@Vignesh025 

Ya i know but i changed some padding suitable for the grid layout

**Comment by Vignesh025** [comment]
Hey, the grid layout is not properly responsive. Here are the changes needed:

Below 580px: 1 card per row
From 580px to 780px: 2 cards per row
From 780px to 1024px: 3 cards per row
Above 1024px: 4 cards per row
Also, there are some UI issues:

The sort button's UI is breaking
The search button's UI breaks after a search
The dropdown button on mobile screens is also breaking
The padding change you made on the campgrounds page is affecting the view page
The 'View' button inside each card should be positioned at the bottom of the box
Please address these issues.

**Pull request closed without merging**
