### PR TITLE
Update env, package.json and the contributors markdown

### PR DESCRIPTION
**Pull request by stacknomad**
## 🔨 Changes Made

- Added and detailed a new `.env.example` file
- Updated the `package.json` file so the `main` entry points to `app.js`
-  Updated the `CONTRIBUTING.md` file with a new step (`step 4`)

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)
A preview image of .env.example
A preview image of .env.example
A preview image of project.json

---

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by stacknomad** [comment]
This pull request is in reference to and addressing [Issue #20](https://github.com/VigneshDevHub/CampX/issues/20).

**Comment by Vignesh025** [comment]
Hi @stacknomad ,

Thank you for submitting the pull request and providing a detailed description of the changes! I really appreciate your initiative in adding a ``.env.example`` file, updating the ``package.json`` entry point, and improving the ``CONTRIBUTING.md`` documentation.

I’d like to ask if you could break these changes into separate commits to maintain clarity and ensure each update can be reviewed independently. For example:

- One commit for the ``.env.example`` file.
- Another commit for the ``package.json`` update.
- A final commit for the changes to ``CONTRIBUTING.md``.

This would make the review process smoother and help with tracking specific changes. Once these commits are made, I'll be happy to review the pull request and merge it into the project.

Thanks again for your contributions! Looking forward to collaborating further.

**Comment by stacknomad** [comment]
Hey @Vignesh025,

Sorry but you're making pull requests more difficult than it has to be. I tried to do what you said and make a pull request on the test branch, but apparently that branch is out of date and the only copy I have is from the main branch. So when I attempt to make the request, it also adds the different changes from main compared to the out-dated test. But I don't know if you have something in test which you don't in main.¯\_(ツ)_/¯

Can you please update the test branch? Thanks!

**Comment by stacknomad** [comment]
My changes are still in sync with the main branch upstream, just not test. Once you sync test and main, then I can make my pull request to test.

**Comment by Vignesh025** [comment]
Hi @stacknomad ,

Apologies for the confusion. The test branch is now in sync with the main branch, so you should be able to proceed with your pull request. Let me know if you encounter any further issues.

Thanks!

**Pull request closed without merging**
