### PR TITLE
[FEATURE] [ Fixes #77] Add search functionality in campgrounds 

### LINKED ISSUE #77: [FEATURE] Add Search Functionality for Camping Locations
**Is your feature request related to a problem? Please describe.**
Yes, currently, if a user wants to search for a camping location, they must manually navigate the map, which can be time-consuming and inefficient.

**Describe the solution you'd like**
I propose adding a search bar that allows users to quickly find camping locations based on their preferences.

**Describe alternatives you've considered**
At this time, no alternatives have been considered.

**Additional context**
While there is a feature for fetching the nearest location, users may wish to explore camping spots elsewhere, making a search function essential for broader flexibility.

### PR DESCRIPTION
**Pull request by Dev-Rishav**
## 📋 Description
Implemented a search box to efficiently search for campgrounds based on user input.

## 🔨 Changes Made

- Added a new searchCampgrounds function in the campgrounds controller to handle campground search based on a query parameter.
- Modified the campgrounds route to include a new GET route for searching campgrounds.
- Updated the index view to include a search bar for users to search for campsites.

## ✅ Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #77

## 📸 Screenshots (if applicable)

 Screenshot from 2024-10-08 00-24-16

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Dev-Rishav** [comment]
@Vignesh025 Please add the relevant gssoc extended and hacktoberfest labels
`gssoc-ext` `hacktoberfest-accepted`.
Thank You!

**Comment by Vignesh025** [comment]
Please create a new CSS file called searchcampground.css in the stylesheets folder inside the public directory, and transfer all your inline styles from the current page to that stylesheet.

**Comment by adarshsingh0103** [comment]
@Dev-Rishav Can you please! assign me to work on this issue.

**Comment by Dev-Rishav** [comment]
@Vignesh025  Done, Please let me know if there are any additional implementations required. Thank You!

**Comment by Vignesh025** [comment]
*Thanks for Contributing!*

**Pull request merged**
