### PR TITLE
[FIX] Capmgrounds page resposiveness for mobile devices

### LINKED ISSUE #264: [UI] Improve the capmgrounds page resposiveness for mobile devices
## Describe the bug
- Capmgrounds page is not resposiveness for mobile devices and tablet devies.

**Screenshots**
camp-res

**Expected behavior**
- Capmgrounds page should responsive for all devices.

## Demo video
2024-10-2212-14-32-ezgif com-video-to-gif-converter

i want to improve its ui,also add label hacktoberfest-accepted and gssoc-ext

### PR DESCRIPTION
**Pull request by roushan-code**
## 📋 Description
This pull request focuses on improving the user interface of the campground search and sorting features. The most important changes include adjustments to padding, border styles, and layout classes to enhance the visual consistency and responsiveness.

## 🔨 Changes Made

* [`public/stylesheets/searchCampground.css`](diffhunk://#diff-0a60fedd6521f3c9f1697c80602c3481ba44b055fa198309753056cf275178d8L29-R29): Reduced the padding of the `#search-button` to improve alignment.

* `views/campgrounds/index.ejs`: 
  * Updated the class attributes of the main container to improve layout responsiveness and alignment across different screen sizes.
  * Modified the padding of the `#sort` dropdown to ensure consistent spacing.
  * Adjusted the border style of the search input field to match the overall design.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #264

## 📸 video
2024-10-2212-14-32-ezgif com-video-to-gif-converter

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hey @roushan-code , please ensure all the buttons are uniform in size for consistency. Thanks!

image

**Comment by roushan-code** [comment]
Hey @Vignesh025 , I have made the changes that you requested. 
The newest Demo video is given below

### Demo Video
2024-10-2615-08-59-ezgif com-video-to-gif-converter

**Comment by Vignesh025** [comment]
Hey @roushan-code , please make the PR to the test branch and not the main branch.

**Comment by roushan-code** [comment]
Hey @Vignesh025, sorry, but I have pushed all the changes in the separate branch. Branch name "fix-campgrounds-page-responsiveness".

- I have checked my main there is no new updated files in public/stylesheets like newCampground.css, searchCampground.css etc.
## Screenshot
img

**Comment by Vignesh025** [comment]
@roushan-code , Please keep your branch as it is; just change the base branch from ``VigneshDevHub:main`` to ``VigneshDevHub:test``

**Comment by roushan-code** [comment]
Hey @Vignesh025, Done

**Pull request merged**
