### PR TITLE
Improved the new campground page

### PR DESCRIPTION
**Pull request by itsadi-24**
## 📋 Description

Screenshot 2024-10-21 155739

Improved the new campground page

### CODE REVIEW

**Comment by itsadi-24** [comment]
Hi @Vignesh025 you can merge it and add the same labels as issue #244 .Thanks!

**Comment by Sowmiyajayakumar** [comment]
Hey @itsadi-24, 
img
here the green outline is not fully covering the box

**Comment by itsadi-24** [comment]
Screenshot 2024-10-21 232123
completely removed the green line,the issue was caused because on getting focused the input boxes get green border,but as '₹' not being a part of input box was causing the issue.
@Vignesh025 @Sowmiyajayakumar now you can merge

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
