### PR TITLE
Solved the documentation issue in the installation file.

### PR DESCRIPTION
**Pull request by ARRY7686**
## 📋 Description

In the Installation Guide, the documentation fails to mention the need to create a MAPBOX_TOKEN in the .env file. Without this token, the server will not start, resulting in an error:
```
Error: Cannot create a client without an access token
    at NodeClient.MapiClient (/path/to/node_modules/@mapbox/mapbox-sdk/lib/classes/mapi-client.js:25:11)
```
When following the installation steps, users encounter an error due to the missing MAPBOX_TOKEN environment variable. The documentation should explicitly instruct users to include the MAPBOX_TOKEN in the .env file to avoid this issue.
## 🔨 Changes Made

Update the Installation Guide to include instructions for setting up the .env file, specifically adding:
```
MAPBOX_TOKEN=<your_mapbox_token_here>
```
This change will ensure that users are aware of the required Mapbox token and avoid runtime errors related to missing environment variables.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues

Fixes Issue Number #19 

- Fixes #

## 📸 Screenshots (if applicable)

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Vignesh025** [comment]
Hi @ARRY7686 ,

Thank you for your pull request! It looks like there are some conflicts that need to be resolved. Could you please make sure your fork is synced with the latest changes from the main repository before resubmitting the PR?

Let me know if you need any help with the process.

Thank you!

**Comment by ARRY7686** [comment]
hey @Vignesh025  i resolved the conflicts pls check and merge now

**Comment by Vignesh025** [comment]
Hey @ARRY7686 ,

I noticed that your pull request removes the CLOUDINARY_KEY and CLOUDINARY_SECRET from the .env file. Please correct this issue, as those are required for the project.

As a suggestion, you could also add instructions on how to obtain those tokens and include them in the .env file to help future contributors. Let me know if you need any help with that.

Thanks!

**Comment by ARRY7686** [comment]
Sure

**Pull request closed without merging**
