### PR TITLE
Fix index page for handeling long description and title field.

### LINKED ISSUE #384: Feat: Problem for heading and description input for campground.
### Describe the feature

As you seen in the attached video. User can give input large heading and description also. Then also your website display the campground description in home page grid card and also the view button contain whole heading.. So in that situation it If the heading and description is too big. The card UI is completely broken. I have several suggestion to prevent this type of vulnerability like -
- what is the necessity to display the whole title in its `view button`  while you already display it's heading in the card.
- Also why display it's whole description field in card while there is already a view page where user can check all of it's details.

### My approaches
- If the title is greater than 25 character then it display a [. . . .] after 25 character in the campground page.
- In my opinion there is no need to display campgrounds description part in campground(home) page. Because there is already Show campground page. Where all the details is displayed. If all details is displayed in  home page. No one could visit this individual show page.
- Also there is no need to show full length title in the `show` button. Because it ruin the card design. Also here already it's title is there. Insted of this only `View Camp site` this type of button is enough.   
- In the Individual View page. All it's full length properties is displayed.
-  Also I add some backend logic to accept the input of heading and description field in `New campground add form` to prevent the very large title and description input.  You tell me the exact length of description and title length that you want!
 
### Add ScreenShots

https://github.com/user-attachments/assets/5744c198-ab74-4736-bd78-9e6693dfcdd3

@Vignesh025  Assign it to me. I think it needs modification. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Suvadip-sana**
## 📋 Description

- I eliminate the description field from index page card.
- Change the view campground button, where initially whole heading is displayed. I change it `View this camp ground`
- Change this view button in secondary color. Because primary color is too contrusty for your website UI
- Your campground schema don't have city field but in index page it's there without any reason. I made changes o n here.
- Add backend logic to prevent the large input of title and description. Title set to max 70 char and description set to max 1000char. I think that's enough.
- Add [...] If the campground heading is more than 25char, in index page. While full length is view inside individual page. It help to display the card in grid format without compromising it's style. Same style(height & width) for all card. As some one working on it in this ISSUE #231 
  

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #384 

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/4823171c-e293-46ec-bd8f-0d58d381b932

---

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

@Vignesh025  Verify it and tell me your opinion.

### CODE REVIEW

**Comment by Suvadip-sana** [comment]
@Vignesh025  See it looks good for small screen device alo because of handeling the heading and eliminate the description field.
image

**Comment by Vignesh025** [comment]
@Suvadip-sana , can you implement the same validation checks for the edit campground?
I'll give you a level-2

**Comment by Suvadip-sana** [comment]
https://github.com/user-attachments/assets/8d7719f6-d6e0-48cb-9eef-2a0b709e90a0



@Vignesh025   Check. I fix it.  Please assign it higher label after verifying it, if possible before marge..

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
