### PR TITLE
added dynamic search

### PR DESCRIPTION
**Pull request by Gauravtb2253**
## 📋 Description

I have added dynamic search functionality in the code
Pls check it

## 🔨 Changes Made

issue #256 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by Sowmiyajayakumar** [comment]
Hey @Gauravtb2253 , dynamic search is not working. please check. when I type something in the search box dynamically the results should appear. But it is not working like that.

**Comment by Gauravtb2253** [comment]
Pls check it now

**Comment by Vignesh025** [comment]
@Gauravtb2253 , It's still not working.

**Comment by Gauravtb2253** [comment]
hello it should work now pls check
try searching using title

**Comment by Vignesh025** [comment]
@Gauravtb2253 The dynamic search is working perfectly fine, but the 'Show Nearest to Me' button isn’t functioning, and the maps aren’t visible. Please resolve that.

**Comment by Gauravtb2253** [comment]
pls check now

**Comment by Vignesh025** [comment]
The issue is still there.

**Comment by Gauravtb2253** [comment]
actually im having some issue in my api key
if possible can you give api key and I could fix the issue properly

**Comment by Vignesh025** [comment]
API keys are sensitive and shouldn’t be shared for security reasons, so I’m unable to provide my Mapbox API key. Let me know if you need guidance on setting up your own!

**Comment by Gauravtb2253** [comment]
pls check now
actually im not having credit card or debit card for mapbox api

**Comment by Vignesh025** [comment]
@Gauravtb2253 ,Start working on the 'Show Nearest to Me' button to make it functional. Meanwhile, if you have a college email, you can sign up for Mapbox with it, and it won’t require card details.

**Pull request closed without merging**
