### PR TITLE
Redesigned Landing Page

### PR DESCRIPTION
**Pull request by itsadi-24**
## 📋 Description

Redesigned and Improved the landing page and also improved its responsiveness

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [✅] My code follows the style guidelines of this project.
- [✅] I have performed a self-review of my own code.
- [✅] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [✅] My changes generate no new warnings.
- [✅] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [✅] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 📸 Screenshots (if applicable)

https://github.com/user-attachments/assets/4441cf21-a1fb-4691-9ca6-820ae5edfc4a

Is it okay?

### CODE REVIEW

**Comment by itsadi-24** [comment]
@Vignesh025 you can merge it and also add the labels hactoberfest-accepted and gssoc-ext.

**Comment by Vignesh025** [comment]
Hey @itsadi-24 , Can you reduce the height of the navbar? It would be better.

**Comment by itsadi-24** [comment]
@Vignesh025 sure!

**Comment by itsadi-24** [comment]
Screenshot 2024-10-20 162255
@Vignesh025 done it

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Pull request merged**
