### PR TITLE
Converted_Images_to_WebP_for_Better_Optimization

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #235 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels! I think this PR deserves level3 label. Please add it i have worked hard to do this! 

@Vignesh025

### CODE REVIEW

**Comment by Sowmiyajayakumar** [comment]
Hey @smog-root , Lazy loading is not implemented. Can you please check that?

**Comment by smog-root** [comment]
Yaa. I tried to implement but it's not working on this! Using webp will slightly optimize your website anywhere.

Webp images are stored in the user browser cookie! After he visited first time!!

But the webp are refreshed every time user
Exits the browser!!

Even though I have made the Website slightly optimized!! @Sowmiyajayakumar

**Comment by Sowmiyajayakumar** [comment]
Please make the PR to test branch

**Comment by smog-root** [comment]
I will make PR by tomorrow morning!! @Sowmiyajayakumar

**Comment by smog-root** [comment]
@Sowmiyajayakumar changed branch to test! 👍

**Comment by Vignesh025** [comment]
*Thankyou for Contributing!*

**Comment by smog-root** [comment]
@Vignesh025 kindly update it to level3. For the issue it is level3!!

**Comment by smog-root** [comment]
@Vignesh025 kindly assign this PR to me! there some issues in my leaderboard profile!

**Comment by Vignesh025** [comment]
@smog-root , assignee does not matter, the assignee is the person who reviews it.

**Pull request merged**
