### PR TITLE
added the code to ..routes/reviews.js

### PR DESCRIPTION
**Pull request by shar2710**
## 📋 Description

Description
Currently, as more reviews are added, the page height increases significantly. This can lead to a poor user experience, especially on smaller screens.

Current Behavior
The reviews section should have a scrollable container that allows users to view all reviews without increasing the overall page height.

Additional Considerations
Consider implementing a mechanism to limit the number of reviews displayed initially and load more on demand using JavaScript.

_**the code has been incorporated into the ..controllers/reviews.js file**_

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

fixes issue #341

### CODE REVIEW

**Comment by shar2710** [comment]
@Vignesh025 i have completed this task. kindly check

**Comment by Vignesh025** [comment]
Hey @shar2710 I’m getting an error when running your code. Please take a look and resolve it.

image

**Comment by shar2710** [comment]
@Vignesh025 i have resolved the error. please check

**Comment by Vignesh025** [comment]
@shar2710 , the feature is not working.

**Pull request closed without merging**
